---
files:
- path: "/Users/dennisschonig/StudioProjects/bt-flutter/.metadata"
  readOnly: false
- path: "/Users/dennisschonig/StudioProjects/bt-flutter/README.md"
  readOnly: false
- path: "/Users/dennisschonig/StudioProjects/bt-flutter/.gitignore"
  readOnly: false
- path: "/Users/dennisschonig/StudioProjects/bt-flutter/pubspec.lock"
  readOnly: false
- path: "/Users/dennisschonig/StudioProjects/bt-flutter/pubspec.yaml"
  readOnly: false
- path: "/Users/dennisschonig/StudioProjects/bt-flutter/.flutter-plugins"
  readOnly: false
- path: "/Users/dennisschonig/StudioProjects/bt-flutter/analysis_options.yaml"
  readOnly: false
- path: "/Users/dennisschonig/StudioProjects/bt-flutter/.flutter-plugins-dependencies"
  readOnly: false
